/**
 * 픽셀 고양이 도트 그림 (먼치킨 — 다리가 짧고 몸이 길다). 오른쪽을 보는 기준.
 * ⚠️ 이 파일은 scripts/make-cat-sprites.mjs 가 만든다. 직접 고치지 말고 그 스크립트를 고쳐서 다시 실행할 것.
 * 글자 = 역할:  O 외곽선  B 몸  H 밝은 털  S 줄무늬(머리·꼬리)  Y 몸 무늬  P 포인트  M 마스크  W 주둥이·가슴  F 발
 *              E 눈동자색  K 동공  L 눈 반짝임  C 감은 눈  N 코  I 귀 안쪽  T 혀  . 투명
 */
export type CatFrame = string[];

export const CAT_W = 30;
export const CAT_H = 18;

export type FrameName =
  | "walkA" | "walkB" | "sit" | "sitWag" | "sleep" | "jump"
  | "groomA" | "groomB" | "stretch" | "eatA" | "eatB" | "crouchA" | "crouchB";

export type CatKind = "taeri" | "jeri";

/** 고양이마다 그림이 다르다 — 태리는 둥글고 통통하게, 제리는 얼굴이 갸름하고 날씬하게 */
export const FRAMES: Record<CatKind, Record<FrameName, CatFrame>> = {
  "taeri": {
    "walkA": [
      "..............................",
      "..............................",
      "..OO...............OO.....OO..",
      ".OPPO.............OPIO...OIPO.",
      "OPSO..............OPPOOOOOPPO.",
      "OPPO.............OGGGSGMGSGGGO",
      ".OPSO............OGGKLGMGKLGGO",
      "..OPOOOOOOOOOOOOOOGGEEMNMEEGGO",
      "...OHHHHHHHHHHHHHOBBBWWWWWBBBO",
      "..OBBYBBBYBBBYBBBOBBBWWWWWBBBO",
      "..OBBYBBBYBBBYBBBYOOOOOOOOOOO.",
      "..OBBBBBBBBBBBBBBBBBBO........",
      "..OBBBBBBBBBBBBBBBBWWO........",
      "...OBBBBBBBBBBBBBBWWO.........",
      "....OBOOOBOOOOOOBOOOBO........",
      "....OBO.OBO....OBO.OBO........",
      "....OFO.OFO....OFO.OFO........",
      "....OOO.OOO....OOO.OOO........"
    ],
    "walkB": [
      "..............................",
      "..............................",
      "..............................",
      "...................OO.....OO..",
      "..................OPIO...OIPO.",
      ".OOO..............OPPOOOOOPPO.",
      "OPSPO............OGGGSGMGSGGGO",
      ".OOPOOOOOOOOOOOOOOGGKLGMGKLGGO",
      "...OHHHHHHHHHHHHHOGGEEMNMEEGGO",
      "..OBBYBBBYBBBYBBBOBBBWWWWWBBBO",
      "..OBBYBBBYBBBYBBBOBBBWWWWWBBBO",
      "..OBBBBBBBBBBBBBBBOOOOOOOOOOO.",
      "..OBBBBBBBBBBBBBBBBWWO........",
      "...OBBBBBBBBBBBBBBWWO.........",
      "....OOBOOBOOOOOOBOOBO.........",
      ".....OBOOFO....OFOOBO.........",
      ".....OFOOOO....OOOOFO.........",
      ".....OOO..........OOO........."
    ],
    "sit": [
      "..............................",
      ".............OO.....OO........",
      "............OPIO...OIPO.......",
      "............OPPOOOOOPPO.......",
      "...........OGGGSGMGSGGGO......",
      "...........OGGKLGMGKLGGO......",
      "...........OGGEEMNMEEGGO......",
      "...........OBBBWWWWWBBBO......",
      "...........OBBBWWWWWBBBO......",
      "...........OOOOOOOOOOOO.......",
      "..........OBBBYBBWWWO.........",
      ".........OBBBBBBBWWWO.........",
      "........OBBYBBBBBWWWWO........",
      "........OBBBBBBBBBWWWO........",
      "........OBBYBBBBBBBBBO........",
      ".OOOOOOOOBBBBBBOBBOBBO........",
      "OPPSPPSPOFFFBBBOFFOFFO........",
      ".OOOOOOOOOOOOOOOOOOOOO........"
    ],
    "sitWag": [
      "..............................",
      ".............OO.....OO........",
      "............OPIO...OIPO.......",
      "............OPPOOOOOPPO.......",
      "...........OGGGSGMGSGGGO......",
      "...........OGGKLGMGKLGGO......",
      "...........OGGEEMNMEEGGO......",
      "...........OBBBWWWWWBBBO......",
      ".....OO....OBBBWWWWWBBBO......",
      "....OPPO...OOOOOOOOOOOO.......",
      "...OPSO...OBBBYBBWWWO.........",
      "...OPPO..OBBBBBBBWWWO.........",
      "....OPSOOBBYBBBBBWWWWO........",
      ".....OPPOBBBBBBBBBWWWO........",
      "......OPOBBYBBBBBBBBBO........",
      ".......OOBBBBBBOBBOBBO........",
      "........OFFFBBBOFFOFFO........",
      "........OOOOOOOOOOOOOO........"
    ],
    "groomA": [
      "..............................",
      "..............................",
      "..............OO.....OO.......",
      ".............OPIO...OIPO......",
      ".............OPPOOOOOPPO......",
      "............OGGGSGMGSGGGO.....",
      "............OGGGGGMGGGGGO.....",
      "............OGGCCMNMCCGGO.....",
      "............OBBBWWWWWBBBO.....",
      "...........OOBBBWWWWWBBBO.....",
      "..........OBBOOOOOOOOOOO......",
      ".........OBBBBBBBWWWOOFFO.....",
      "........OBBYBBBBBWWWWOFFO.....",
      "........OBBBBBBBBBWWOBBO......",
      "........OBBYBBBBBBBBOBO.......",
      ".OOOOOOOOBBBBBBOBBOBOO........",
      "OPPSPPSPOFFFBBBOFFOFFO........",
      ".OOOOOOOOOOOOOOOOOOOOO........"
    ],
    "groomB": [
      "..............................",
      "..............................",
      "..............................",
      "..............OO.....OO.......",
      ".............OPIO...OIPO......",
      ".............OPPOOOOOPPO......",
      "............OGGGSGMGSGGGO.....",
      "............OGGGGGMGGGGGO.....",
      "............OGGCCMNMCCGGO.....",
      "...........OOBBBWWWWWBBBO.....",
      "..........OBOBBBWWTWWBBBO.....",
      ".........OBBBOOOOOTOOOOO......",
      "........OBBYBBBBBWWWWOFFO.....",
      "........OBBBBBBBBBWWWOFFO.....",
      "........OBBYBBBBBBBBOBBO......",
      ".OOOOOOOOBBBBBBOBBOBOBO.......",
      "OPPSPPSPOFFFBBBOFFOFOO........",
      ".OOOOOOOOOOOOOOOOOOOOO........"
    ],
    "stretch": [
      "..............................",
      "..OO..........................",
      ".OPPO.........................",
      "OPSO..........................",
      "OPPO..........................",
      ".OPSOOOOOO....................",
      "..OOHHHHHBOOO......OO.....OO..",
      "...OBBYBBBBBBOOO..OPIO...OIPO.",
      "...OBBYBBBYBBBBBOOOPPOOOOOPPO.",
      "...OBBBBBBYBBBYBBOGGGSGMGSGGGO",
      "...OBBBBBBBBBBYBBOGGGGGMGGGGGO",
      "...OBBOOOBBBBBBBBOGGCCMNMCCGGO",
      "...OBBO..OOBBBBBBOBBBWWWWWBBBO",
      "...OBBO....OOOBBBOBBBWWWWWBBBO",
      "...OBBO.......OOBBOOOOOOOOOOO.",
      "...OBBO.........OBBBBBBBBFFO..",
      "..OFFFO..........OOOOOOOOOO...",
      "..OOOOO......................."
    ],
    "sleep": [
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      ".......OOOOOOOOOOOO.....OO....",
      ".....OOHHHHHHHHHOPIO...OIPO...",
      "....OBBBYBBBYBBBOPPOOOOOPPO...",
      "...OBBBBYBBBYBBOGGGSGMGSGGGO..",
      "..OBBBBBBBBBBBBOGGGGGMGGGGGO..",
      "..OBBBBBBBBBBBBOGGCCMNMCCGGO..",
      "..OBBBBBBBBBBBBOBBBWWWWWBBBO..",
      "..OPPPPPPPPPPPPOBBBWWWWWBBBO..",
      "..OPSPPSPPSPPPPOOOOOOOOOOOO...",
      "...OOOOOOOOOOOOO.............."
    ],
    "crouchA": [
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      "...................OO.....OO..",
      "..................OPIO...OIPO.",
      ".....OOOOOOOOOOOOOOPPOOOOOPPO.",
      "OOOOOHHHHHHHHHHHHOGGGSGMGSGGGO",
      "OPSOBBYBBBYBBBYBBOGGKLGMGKLGGO",
      ".OOOBBYBBBYBBBYBBOGGEEMNMEEGGO",
      "...OBBBBBBBBBBBBBOBBBWWWWWBBBO",
      "...OBBBBBBBBBBBBBOBBBWWWWWBBBO",
      "....OOBOBOBOBBBBOBOOOOOOOOOOO.",
      ".....OFOOOFOOOOOOFOOOFO.......",
      ".....OOO.OOO....OOO.OOO......."
    ],
    "crouchB": [
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      "...................OO.....OO..",
      ".OOOOOOOOOOOOOOOOOOPIO...OIPO.",
      "OPSOHHHHHHHHHHHHHHOPPOOOOOPPO.",
      ".OOBBYBBBYBBBYBBBOGGGSGMGSGGGO",
      "..OBBYBBBYBBBYBBBOGGKLGMGKLGGO",
      "..OBBBBBBBBBBBBBBOGGEEMNMEEGGO",
      "..OBBBBBBBBBBBBBBOBBBWWWWWBBBO",
      "...OBBBBBBBBBBBBBOBBBWWWWWBBBO",
      "....OBOOOBOOOOOOOBOOOOOOOOOOO.",
      "....OFO.OFO.....OFO.OFO.......",
      "....OOO.OOO.....OOO.OOO......."
    ],
    "eatA": [
      "..............................",
      "..............................",
      "..OO..........................",
      ".OPPO.........................",
      "OPSO..........................",
      "OPPO..........................",
      ".OPSO.........................",
      "..OPOOOOOOOOOOOOOOOO..........",
      "...OHHHHHHHHHHHHHHHOO.....OO..",
      "..OBBYBBBYBBBYBBBYOPIO...OIPO.",
      "..OBBYBBBYBBBYBBBYOPPOOOOOPPO.",
      "..OBBBBBBBBBBBBBBOGGGSGMGSGGGO",
      "..OBBBBBBBBBBBBBBOGGGGGMGGGGGO",
      "...OBBBBBBBBBBBBBOGGCCMNMCCGGO",
      "....OBOOOBOOOOOOBOBBBWWWWWBBBO",
      "....OBO.OBO....OBOBBBWWWWWBBBO",
      "....OFO.OFO....OFOOOOOOOOOOOO.",
      "....OOO.OOO....OOO.OOO........"
    ],
    "eatB": [
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      ".OOO..........................",
      "OPSPO.........................",
      ".OOPOOOOOOOOOOOOOOOO..........",
      "...OHHHHHHHHHHHHHHHBO.........",
      "..OBBYBBBYBBBYBBBYBOOO....OO..",
      "..OBBYBBBYBBBYBBBYOPIO...OIPO.",
      "..OBBBBBBBBBBBBBBBOPPOOOOOPPO.",
      "..OBBBBBBBBBBBBBBOGGGSGMGSGGGO",
      "...OBBBBBBBBBBBBBOGGGGGMGGGGGO",
      "....OBOOOBOOOOOOBOGGCCMNMCCGGO",
      "....OBO.OBO....OBOBBBWWWWWBBBO",
      "....OFO.OFO....OFOBBBWWTWWBBBO",
      "....OOO.OOO....OOOOOOOOTOOOOO."
    ],
    "jump": [
      "...................OO.....OO..",
      "..................OPIO...OIPO.",
      "..................OPPOOOOOPPO.",
      ".................OGGGSGMGSGGGO",
      ".....OOOOOOOOOOOOOGGKLGMGKLGGO",
      "....OHHHHHHHHHHHHOGGEEMNMEEGGO",
      "OOOOBBYBBBYBBBYBBOBBBWWWWWBBBO",
      "OPSOBBYBBBYBBBYBBOBBBWWWWWBBBO",
      ".OOOBBBBBBBBBBBBBBOOOOOOOOOOO.",
      "...OBBBBBBBBBBBBBBBBWWO.......",
      "...OBOBOBOBBBBBBBOBOWOBO......",
      "..OBOOOBOOOOOOOOOOOBO.OBO.....",
      ".OFO.OFO...........OFO.OFO....",
      ".OO..OO.............OO..OO....",
      "..............................",
      "..............................",
      "..............................",
      ".............................."
    ]
  },
  "jeri": {
    "walkA": [
      "..............................",
      "..............................",
      "...................O.......O..",
      "..................OPO.....OPO.",
      "..OO..............OPIO...OIPO.",
      ".OPPO.............OPPOOOOOPPO.",
      "OPSO..............OGGSGMGSGGO.",
      "OPPO..............OGKLGMGKLGO.",
      ".OPSO.............OGEEMNMEEGO.",
      "..OPOOOOOOOOOOOOOOOOBWWWWWBO..",
      "...OHHHHHHHHHHHHHHHBOOWWWOO...",
      "..OBBYBBBYBBBYBBBYBBBOOOO.....",
      "..OBBBBBBBBBBBBBBBBWWO........",
      "...OBBBBBBBBBBBBBBWWO.........",
      "....OBOOOBOOOOOOBOOOBO........",
      "....OBO.OBO....OBO.OBO........",
      "....OFO.OFO....OFO.OFO........",
      "....OOO.OOO....OOO.OOO........"
    ],
    "walkB": [
      "..............................",
      "..............................",
      "..............................",
      "...................O.......O..",
      "..................OPO.....OPO.",
      "..................OPIO...OIPO.",
      "..................OPPOOOOOPPO.",
      ".OOO..............OGGSGMGSGGO.",
      "OPSPO.............OGKLGMGKLGO.",
      ".OOPOOOOOOOOOOOOOOOGEEMNMEEGO.",
      "...OHHHHHHHHHHHHHHHOBWWWWWBO..",
      "..OBBYBBBYBBBYBBBYBBOOWWWOO...",
      "..OBBBBBBBBBBBBBBBBWWOOOO.....",
      "...OBBBBBBBBBBBBBBWWO.........",
      "....OOBOOBOOOOOOBOOBO.........",
      ".....OBOOFO....OFOOBO.........",
      ".....OFOOOO....OOOOFO.........",
      ".....OOO..........OOO........."
    ],
    "sit": [
      "............O.......O.........",
      "...........OPO.....OPO........",
      "...........OPIO...OIPO........",
      "...........OPPOOOOOPPO........",
      "...........OGGSGMGSGGO........",
      "...........OGKLGMGKLGO........",
      "...........OGEEMNMEEGO........",
      "............OBWWWWWBO.........",
      ".............OOWWWOO..........",
      "............OBBOOOO...........",
      "...........OBBYBWWO...........",
      "...........OBBBBWWWO..........",
      "..........OBYBBBWWWO..........",
      "..........OBBBBBBWWO..........",
      ".........OBBYBBBBBBO..........",
      "..OOOOOOOOBBBBOBBOBO..........",
      ".OPPSPPSPOFFFBOFFOFFO.........",
      "..OOOOOOOOOOOOOOOOOOO........."
    ],
    "sitWag": [
      "............O.......O.........",
      "...........OPO.....OPO........",
      "...........OPIO...OIPO........",
      "...........OPPOOOOOPPO........",
      "...........OGGSGMGSGGO........",
      "...........OGKLGMGKLGO........",
      "...........OGEEMNMEEGO........",
      "............OBWWWWWBO.........",
      "......OO.....OOWWWOO..........",
      ".....OPPO...OBBOOOO...........",
      "....OPSO...OBBYBWWO...........",
      "....OPPO...OBBBBWWWO..........",
      ".....OPSO.OBYBBBWWWO..........",
      "......OPPOOBBBBBBWWO..........",
      ".......OPOBBYBBBBBBO..........",
      "........OOBBBBOBBOBO..........",
      ".........OFFFBOFFOFFO.........",
      ".........OOOOOOOOOOOO........."
    ],
    "groomA": [
      "..............................",
      ".............O.......O........",
      "............OPO.....OPO.......",
      "............OPIO...OIPO.......",
      "............OPPOOOOOPPO.......",
      "............OGGSGMGSGGO.......",
      "............OGGGGMGGGGO.......",
      "............OGCCMNMCCGO.......",
      ".............OBWWWWWBO........",
      "............OBOOWWWOOO........",
      "...........OBBYBOOOOFFO.......",
      "...........OBBBBWWWOFFO.......",
      "..........OBYBBBWWOBBO........",
      "..........OBBBBBBWOBO.........",
      ".........OBBYBBBBBOO..........",
      "..OOOOOOOOBBBBOBBOBO..........",
      ".OPPSPPSPOFFFBOFFOFFO.........",
      "..OOOOOOOOOOOOOOOOOOO........."
    ],
    "groomB": [
      "..............................",
      "..............................",
      ".............O.......O........",
      "............OPO.....OPO.......",
      "............OPIO...OIPO.......",
      "............OPPOOOOOPPO.......",
      "............OGGSGMGSGGO.......",
      "............OGGGGMGGGGO.......",
      "............OGCCMNMCCGO.......",
      "............OOBWWWWWBO........",
      "...........OBBOOWTWOOO........",
      "...........OBBBBOTOOFFO.......",
      "..........OBYBBBWWWOFFO.......",
      "..........OBBBBBBWOBBO........",
      ".........OBBYBBBBBOBO.........",
      "..OOOOOOOOBBBBOBBOOO..........",
      ".OPPSPPSPOFFFBOFFOFFO.........",
      "..OOOOOOOOOOOOOOOOOOO........."
    ],
    "stretch": [
      "..............................",
      "..OO..........................",
      ".OPPO.........................",
      "OPSO..........................",
      "OPPO..........................",
      ".OPSOOOOOO.........O.......O..",
      "..OOHHHHHBOOO.....OPO.....OPO.",
      "...OBBYBBBBBBOOO..OPIO...OIPO.",
      "...OBBYBBBYBBBBBOOOPPOOOOOPPO.",
      "...OBBBBBBYBBBYBBBOGGSGMGSGGO.",
      "...OBBBBBBBBBBYBBBOGGGGMGGGGO.",
      "...OBBOOOBBBBBBBBBOGCCMNMCCGO.",
      "...OBBO..OOBBBBBBBBOBWWWWWBO..",
      "...OBBO....OOOBBBBBOOOWWWOO...",
      "...OBBO.......OOBBBBOOOOOOO...",
      "...OBBO.........OBBBBBBBBFFO..",
      "..OFFFO..........OOOOOOOOOO...",
      "..OOOOO......................."
    ],
    "sleep": [
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      "................O.......O.....",
      "...............OPO.....OPO....",
      ".......OOOOOOOOOPIO...OIPO....",
      ".....OOHHHHHHHHOPPOOOOOPPO....",
      "....OBBBYBBBYBBOGGSGMGSGGO....",
      "...OBBBBBBBBBBBOGGGGMGGGGO....",
      "..OBBBBBBBBBBBBOGCCMNMCCGO....",
      "..OPPPPPPPPPPPPBOBWWWWWBO.....",
      "..OPSPPSPPSPPPPOOOOWWWOO......",
      "...OOOOOOOOOOOOO...OOO........"
    ],
    "crouchA": [
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      "...................O.......O..",
      "..................OPO.....OPO.",
      "..................OPIO...OIPO.",
      "..................OPPOOOOOPPO.",
      "..................OGGSGMGSGGO.",
      "OOOOOOOOOOOOOOOOOOOGKLGMGKLGO.",
      "OPSPOHHHHHHHHHHHHHOGEEMNMEEGO.",
      ".OOOBBYBBBYBBBYBBBYOBWWWWWBO..",
      "...OBBBBBBBBBBBBBBBBOOWWWOO...",
      "....OOBOBOBOBBBBOBOWOBOOO.....",
      ".....OFOOOFOOOOOOFOOOFO.......",
      ".....OOO.OOO....OOO.OOO......."
    ],
    "crouchB": [
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      "...................O.......O..",
      "..................OPO.....OPO.",
      "..................OPIO...OIPO.",
      ".OOO..............OPPOOOOOPPO.",
      "OPSPOOOOOOOOOOOOOOOGGSGMGSGGO.",
      ".OOOHHHHHHHHHHHHHHOGKLGMGKLGO.",
      "..OBBYBBBYBBBYBBBYOGEEMNMEEGO.",
      "..OBBBBBBBBBBBBBBBBOBWWWWWBO..",
      "...OBBBBBBBBBBBBBBWWOOWWWOO...",
      "....OBOOOBOOOOOOOBOOOBOOO.....",
      "....OFO.OFO.....OFO.OFO.......",
      "....OOO.OOO.....OOO.OOO......."
    ],
    "eatA": [
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      "..OO..........................",
      ".OPPO.........................",
      "OPSO..........................",
      "OPPO................O.......O.",
      ".OPSO..............OPO.....OPO",
      "..OPOOOOOOOOOOOOOOOOPIO...OIPO",
      "...OHHHHHHHHHHHHHHHOPPOOOOOPPO",
      "..OBBYBBBYBBBYBBBYBOGGSGMGSGGO",
      "..OBBBBBBBBBBBBBBBBOGGGGMGGGGO",
      "...OBBBBBBBBBBBBBBWOGCCMNMCCGO",
      "....OBOOOBOOOOOOBOOOOBWWWWWBO.",
      "....OBO.OBO....OBO.OBOOWWWOO..",
      "....OFO.OFO....OFO.OFO.OOO....",
      "....OOO.OOO....OOO.OOO........"
    ],
    "eatB": [
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      ".OOO..........................",
      "OPSPO...............O.......O.",
      ".OOPOOOOOOOOOOOOOOOOPO.....OPO",
      "...OHHHHHHHHHHHHHHHOPIO...OIPO",
      "..OBBYBBBYBBBYBBBYBOPPOOOOOPPO",
      "..OBBBBBBBBBBBBBBBBOGGSGMGSGGO",
      "...OBBBBBBBBBBBBBBWOGGGGMGGGGO",
      "....OBOOOBOOOOOOBOOOGCCMNMCCGO",
      "....OBO.OBO....OBO.OOBWWWWWBO.",
      "....OFO.OFO....OFO.OFOOWTWOO..",
      "....OOO.OOO....OOO.OOO.OTO...."
    ],
    "jump": [
      "....................O.......O.",
      "...................OPO.....OPO",
      "...................OPIO...OIPO",
      "...................OPPOOOOOPPO",
      "...................OGGSGMGSGGO",
      "...................OGKLGMGKLGO",
      ".....OOOOOOOOOOOOOOOGEEMNMEEGO",
      "OOOOOHHHHHHHHHHHHHHHOBWWWWWBO.",
      "OPSOBBYBBBYBBBYBBBYBBOOWWWOO..",
      ".OOOBBBBBBBBBBBBBBBBWWOOOO....",
      "...OBOBOBOBBBBBBBOBOWOBO......",
      "..OBOOOBOOOOOOOOOOOBO.OBO.....",
      ".OFO.OFO...........OFO.OFO....",
      ".OO..OO.............OO..OO....",
      "..............................",
      "..............................",
      "..............................",
      ".............................."
    ]
  }
};

/** 고양이 이름 (실제 고양이 태리·제리) */
export const CAT_NAMES: Record<CatKind, string> = { taeri: "태리", jeri: "제리" };

/** 역할 글자 → 색 */
export const PALETTES: Record<CatKind, Record<string, string>> = {
  "taeri": {
    "O": "#a9794a",
    "B": "#f4d3ab",
    "G": "#f4d3ab",
    "H": "#fbe6cb",
    "S": "#eabf91",
    "P": "#f1cb9f",
    "M": "#f8dcb9",
    "W": "#fffaf1",
    "F": "#fffaf1",
    "E": "#d08a2e",
    "K": "#2a1c10",
    "L": "#ffffff",
    "C": "#a9794a",
    "N": "#ee9d90",
    "I": "#f6bfb6",
    "T": "#f08f9a",
    "Y": "#eec79c"
  },
  "jeri": {
    "O": "#5a4f57",
    "B": "#ecdfd2",
    "G": "#9d9199",
    "H": "#f8f0e6",
    "S": "#8a7e87",
    "P": "#93878f",
    "M": "#d9cdc6",
    "W": "#fffdf8",
    "F": "#d5c9c8",
    "E": "#5fb0ea",
    "K": "#1d3b55",
    "L": "#ffffff",
    "C": "#463c43",
    "N": "#b08a8c",
    "I": "#c9a9ad",
    "T": "#ec8fa0",
    "Y": "#e3d4c6"
  }
};

/** 밥그릇·물그릇 — 채워진 정도(0~3)별 그림 */
export type BowlKind = "food" | "water";
export const BOWL_W = 12;
export const BOWL_H = 6;
export const BOWLS: Record<BowlKind, CatFrame[]> = {
  "food": [
    [
      "............",
      "............",
      "RRRRRRRRRRRR",
      "RDDDDDDDDDDR",
      ".RDDDDDDDDR.",
      "..RRRRRRRR.."
    ],
    [
      "............",
      "....KKKK....",
      "RRRRRRRRRRRR",
      "RDDDDDDDDDDR",
      ".RDDDDDDDDR.",
      "..RRRRRRRR.."
    ],
    [
      "............",
      "..KKKKKKKK..",
      "RRRRRRRRRRRR",
      "RDDDDDDDDDDR",
      ".RDDDDDDDDR.",
      "..RRRRRRRR.."
    ],
    [
      "....KKKK....",
      "..KJKKKJKK..",
      "RRRRRRRRRRRR",
      "RDDDDDDDDDDR",
      ".RDDDDDDDDR.",
      "..RRRRRRRR.."
    ]
  ],
  "water": [
    [
      "............",
      "............",
      "RRRRRRRRRRRR",
      "RGGGGGGGGGGR",
      ".RGGGGGGGGR.",
      "..RRRRRRRR.."
    ],
    [
      "............",
      "............",
      "RRRRRRRRRRRR",
      "RGGGGGGGGGGR",
      ".RGWWWWWWGR.",
      "..RRRRRRRR.."
    ],
    [
      "............",
      "............",
      "RRRRRRRRRRRR",
      "RGGGGGGGGGGR",
      ".RWWWWWWWWR.",
      "..RRRRRRRR.."
    ],
    [
      "............",
      "............",
      "RRRRRRRRRRRR",
      "RWWLWWWWWWWR",
      ".RWWWWWWWWR.",
      "..RRRRRRRR.."
    ]
  ]
};
export const BOWL_PALETTES: Record<BowlKind, Record<string, string>> = {
  "food": {
    "R": "#b96a45",
    "D": "#e08f63",
    "K": "#8a5a2b",
    "J": "#a9743a"
  },
  "water": {
    "R": "#6f9cc4",
    "G": "#dcebf7",
    "W": "#8cc8f2",
    "L": "#ffffff"
  }
};

/** 주인 이윤 — 츄르를 주러 온다 */
export type OwnerFrame = "stand" | "walkA" | "walkB" | "give" | "wave";
export const OWNER_NAME = "이윤";
export const OWNER_W = 20;
export const OWNER_H = 24;
export const OWNER_FRAMES: Record<OwnerFrame, CatFrame> = {
  "stand": [
    ".....OOOOOO.........",
    "....OHHhhHHO........",
    "...OHHhHHHHHO.......",
    "...OHHHHHHHHO.......",
    "..OHHHHHHHHHHO......",
    "..OHHSSHSSSHHO......",
    "..OHSSSSSSSSHO......",
    "..OHSEWSSEWSHO......",
    "..OHSsSSSSsSHO......",
    "..OHHSSSsSSHHO......",
    "..OHHOSSSSOHHO......",
    "..OHHOTTTTOHHO......",
    "..OHOTTTTTTOHO......",
    ".OOTTTTTTTTTTOO.....",
    ".OTTOTTTTTTOTTO.....",
    ".OSSOTTTTTTOSSO.....",
    ".OSSOKKKKKKOSSO.....",
    "..OOKKKKKKKKOO......",
    "...OOOOOOOOOO.......",
    ".....OSOOSO.........",
    ".....OSOOSO.........",
    ".....OSOOSO.........",
    "....OBBOOBBO........",
    "....OOOOOOOO........"
  ],
  "walkA": [
    ".....OOOOOO.........",
    "....OHHhhHHO........",
    "...OHHhHHHHHO.......",
    "...OHHHHHHHHO.......",
    "..OHHHHHHHHHHO......",
    "..OHHSSHSSSHHO......",
    "..OHSSSSSSSSHO......",
    "..OHSEWSSEWSHO......",
    "..OHSsSSSSsSHO......",
    "..OHHSSSsSSHHO......",
    "..OHHOSSSSOHHO......",
    "..OHHOTTTTOHHO......",
    "..OHOTTTTTTOHO......",
    ".OOTTTTTTTTTTOO.....",
    ".OTTOTTTTTTOTTO.....",
    ".OSSOTTTTTTOSSO.....",
    ".OSSOKKKKKKOSSO.....",
    "..OOKKKKKKKKOO......",
    "...OOOOOOOOOO.......",
    "....OSO..OSO........",
    "...OSO....OSO.......",
    "...OSO....OSO.......",
    "..OBBO....OBBO......",
    "..OOOO....OOOO......"
  ],
  "walkB": [
    "....................",
    ".....OOOOOO.........",
    "....OHHhhHHO........",
    "...OHHhHHHHHO.......",
    "...OHHHHHHHHO.......",
    "..OHHHHHHHHHHO......",
    "..OHHSSHSSSHHO......",
    "..OHSSSSSSSSHO......",
    "..OHSEWSSEWSHO......",
    "..OHSsSSSSsSHO......",
    "..OHHSSSsSSHHO......",
    "..OHHOSSSSOHHO......",
    "..OHHOTTTTOHHO......",
    "..OHOTTTTTTOHO......",
    ".OOTTTTTTTTTTOO.....",
    ".OTTOTTTTTTOTTO.....",
    ".OSSOTTTTTTOSSO.....",
    ".OSSOKKKKKKOSSO.....",
    "..OOKKKKKKKKOO......",
    "...OOOOSSOOOO.......",
    "......OSSO..........",
    "......OSSO..........",
    ".....OBBBBO.........",
    ".....OOOOOO........."
  ],
  "give": [
    "....................",
    "....................",
    "....................",
    "....................",
    ".....OOOOOO.........",
    "....OHHhhHHO........",
    "...OHHhHHHHHO.......",
    "...OHHHHHHHHO.......",
    "..OHHHHHHHHHHO......",
    "..OHHSSHSSSHHO......",
    "..OHSSSSSSSSHO......",
    "..OHSEWSSEWSHO......",
    "..OHSsSSSSsSHO......",
    "..OHHSSSsSSHHO......",
    "..OHHOSSSSOHHO......",
    "..OHHOTTTTOHHO......",
    "..OHOTTTTTTOOOOOOO..",
    ".OOTTTTTTTTTTTTSSCCc",
    ".OTTOTTTTTTOOOOSSCCc",
    ".OSSOTTTTTTO...OO...",
    "..OKKKKKKKKKO.......",
    ".OKKKKKKKKKKKO......",
    ".OBBOOOOOOOBBO......",
    ".OOOOOOOOOOOOO......"
  ],
  "wave": [
    ".....OOOOOO.........",
    "....OHHhhHHO........",
    "...OHHhHHHHHO.......",
    "...OHHHHHHHHO.......",
    "..OHHHHHHHHHHO......",
    "..OHHSSHSSSHHO......",
    "..OHSSSSSSSSHO......",
    "..OHSEWSSEWSHO......",
    "..OHSsSSSSsSHO......",
    "..OHHSSSsSSHHO......",
    "..OHHOSSSSOHHO......",
    "..OHHOTTTTOHHO.SSO..",
    "..OHOTTTTTTOHOOTTO..",
    ".OOTTTTTTTTTTOTTO...",
    ".OTTOTTTTTTOTTO.....",
    ".OSSOTTTTTTOSO......",
    ".OSSOKKKKKKOO.......",
    "..OOKKKKKKKKO.......",
    "...OOOOOOOOOO.......",
    ".....OSOOSO.........",
    ".....OSOOSO.........",
    ".....OSOOSO.........",
    "....OBBOOBBO........",
    "....OOOOOOOO........"
  ]
};
export const OWNER_PALETTE: Record<string, string> = {
  "O": "#3a2a2a",
  "H": "#4a3028",
  "Z": "#cfe0f2",
  "z": "#eaf3fc",
  "h": "#7a5443",
  "S": "#fbdcc4",
  "s": "#f4a09a",
  "E": "#2a1c1c",
  "W": "#ffffff",
  "T": "#f7b8c8",
  "t": "#ec9bb0",
  "K": "#2f3f63",
  "B": "#7a4a3a",
  "C": "#f39a3d",
  "c": "#fff1d6",
  "e": "#3a2a2a"
};
export const CHURU_ICON: CatFrame = [
  "......Oc",
  ".....OCc",
  "....OCCO",
  "...OCCO.",
  "..OCCO..",
  ".OCCO...",
  "OCCO....",
  "OOO....."
];

/** 낮잠 — 베개 베고 누운 이윤 (가로로 길어서 따로) */
export const NAP_W = 46;
export const NAP_H = 14;
export const OWNER_NAP: CatFrame = [
  "..............................................",
  "....ZZZZZZZZZZ................................",
  "...ZzzzzzzzzzzZ...............................",
  "...ZzOHHHHHHHHOZ..............................",
  "...ZzOHHHHHHHHHOOOOOOOOOOOOOOOOOOOOOOOOOO.....",
  "...ZzOHHSSSSSSHOTTTTTTTTTTTTKKKKKKKKSSSSSSO...",
  "...ZzOHeSSSSSeHOTTTTTTTTTTTTKKKKKKKKSSSSSSSO..",
  "...ZzOHSSSSSSSHOTTTTTTTTTTTTKKKKKKKKSSSSSSSO..",
  "....ZOHHSSSSSHHOTTTTTTTTTTTTKKKKKKKKSSSSSSO...",
  "....ZZOHHHHHHHOOOOOOOOOOOOOOOOOOOOOOOOOOO.....",
  ".....ZZZZZZZZZZ...............................",
  "..............................................",
  ".............................................."
];
export const PILLOW_W = 8;
export const PILLOW_H = 5;
export const PILLOW: CatFrame = [
  ".OOOOOO.",
  "OZzzzzZO",
  "OZzzzzZO",
  "OZZZZZZO",
  ".OOOOOO."
];

/** 밥·물을 따라 주는 모습 — 기울인 사료 봉지 / 생수병과 떨어지는 줄기 */
export const POUR_W = 16;
export const POUR_H = 17;
export const POUR_FRAMES: Record<"foodA" | "foodB" | "waterA" | "waterB", CatFrame> =
  {
  "foodA": [
    "...OOOOOOO......",
    "..OKKKKKKKO.....",
    "..OKKKKKKKO.....",
    "..OKkkkkkKO.....",
    "..OKkddkkKO.....",
    "..OKkkkkkKO.....",
    "..OKKKKKKKO.....",
    "..OKKKKKKKO.....",
    "...OKKKKKO......",
    "....OKKKO.......",
    ".....OOO........",
    "....d..d........",
    ".....d..........",
    "....d.d........."
  ],
  "foodB": [
    "...OOOOOOO......",
    "..OKKKKKKKO.....",
    "..OKKKKKKKO.....",
    "..OKkkkkkKO.....",
    "..OKkddkkKO.....",
    "..OKkkkkkKO.....",
    "..OKKKKKKKO.....",
    "..OKKKKKKKO.....",
    "...OKKKKKO......",
    "....OKKKO.......",
    ".....OOO........",
    ".....d.d........",
    "....d...........",
    ".....d.d........"
  ],
  "waterA": [
    "...PPPPPP.......",
    "..PQqqqqQP......",
    "..PQqqqqQP......",
    "..PQwwwwQP......",
    "..PQwwwwQP......",
    "..PQqqqqQP......",
    "..PQqqqqQP......",
    "...PQqqQP.......",
    "....PqqP........",
    "....PqqP........",
    ".....PP.........",
    ".....b..........",
    ".....b..........",
    "....b..........."
  ],
  "waterB": [
    "...PPPPPP.......",
    "..PQqqqqQP......",
    "..PQqqqqQP......",
    "..PQwwwwQP......",
    "..PQwwwwQP......",
    "..PQqqqqQP......",
    "..PQqqqqQP......",
    "...PQqqQP.......",
    "....PqqP........",
    "....PqqP........",
    ".....PP.........",
    ".....b..........",
    "....b...........",
    "....b..........."
  ]
};
export const POUR_PALETTE: Record<string, string> = {
  "O": "#6b4a25",
  "K": "#c98f4e",
  "k": "#f0dcc0",
  "d": "#7a4a18",
  "P": "#4d86b8",
  "Q": "#eaf6ff",
  "q": "#8ccdf2",
  "w": "#ffffff",
  "b": "#7cc4ef"
};
export const NAP_ICON: CatFrame = [
  "..OOOO..",
  ".OZzzZO.",
  "OZzOHOzZ",
  "OZzHSSHO",
  "OZzHCCHO",
  ".OZzzZO.",
  "..OOOO.."
];

/** 낚싯대 장난감 — 놀아줄 때 이윤이 흔든다 */
export const TOY_W = 16;
export const TOY_H = 12;
export const TOY_FRAMES: Record<"toyA" | "toyB", CatFrame> = {
  "toyA": [
    "....S...........",
    "....rS..........",
    "....r.S.........",
    "....r..S........",
    "...fFf..S.......",
    "..fFFFf..S......",
    "...fFf....S.....",
    "....f......S....",
    "............S...",
    ".............S..",
    "..............S.",
    "...............S"
  ],
  "toyB": [
    "....S...........",
    "...r.S..........",
    "..r...S.........",
    ".r.....S........",
    "fFf.....S.......",
    "FFFf.....S......",
    "fFf.......S.....",
    ".f.........S....",
    "............S...",
    ".............S..",
    "..............S.",
    "...............S"
  ]
};
export const TOY_PALETTE: Record<string, string> = {
  "S": "#8a5a2b",
  "r": "#8a8175",
  "F": "#ef6f8f",
  "f": "#f9b3c4"
};
export const TOY_ICON: CatFrame = [
  "..fFf.",
  ".fFFFf",
  "..fFf.",
  "...r..",
  "..r...",
  ".r....",
  "S....."
];
